
spring.datasource.url=jdbc:postgresql://postgres:5432/docker
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
storageStrategy=object-storage
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword

server.port=8080
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

minio.endpoint=http://minio:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket-name=bunucci
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true